---
- hosts: Borders
  gather_facts: False
  collections:
    - dellemc.os10
  tasks:
  - name: "Conf leaking Vrf Ext"
    os10_config:
      lines: 
        - ip route-export 60000:60000
        - ip route-import 40000:40000
        - ip route-import 20000:20000
      parents: ['ip vrf Ext']
