---
- hosts: dellos10
  gather_facts: False
  collections:
    - dellemc.os10
  tasks:
   - name: "Backup-conf"
     os10_config:
       backup: yes
       backup_options:
         filename: "{{inventory_hostname}}.bkp"
         dir_path: ./backup-conf
