- hosts: leaf1
  gather_facts: false
  connection: network_cli
  collections:
    - dellemc.os10
  tasks:
  - name: "Set hostname and configure VLAN 10"
    os10_config:
     commands:
       - hostname {{hostname}}
       - interface vlan 10
    register: set_hostname_vlan
  - debug: var=set_hostname_vlan
