- hosts: Leaves,Borders
  connection: local
  gather_facts: no
  vars_prompt:
    - name: vlan_id
      prompt: Please enter vlan id
      private: no
    - name: tenant_id
      prompt: Please enter tenant for vlan
      private: no
    - name: network_ip_mask
      prompt: Please enter network ip & mask for vlan (X.X.X.X/X)
      private: no
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: 'Vlan {{vlan_id}} for tenant {{tenant_id}} with ip and mask {{network_ip_mask}} will be created'
    - name: Building Var file
      template:
        src=template/create-vlan.j2
        dest=tmp/vlan.yaml

- hosts: Leaves,Borders
  gather_facts: no
  connection: network_cli
  vars_files:
    - ./tmp/vlan.yaml
  collections:
    - dellemc.os10
  roles:
    - os10_interface
    - os10_vxlan

- hosts: Leaves,Borders
  connection: local
  gather_facts: no
  tasks:
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: tmp/vlan.yaml
        state: absent
