---
- hosts: Borders
  gather_facts: False
  collections:
    - dellemc.os10
  tasks:
  - name: "Conf OSPF Router"
    os10_config:
      lines: 
        - router ospf 100
        - router ospf 101 vrf Blue
  - name: "Conf OSPF Default"
    os10_config:
      lines: 
        - router-id "{{inventory_hostname[-1]}}.{{inventory_hostname[-1]}}.{{inventory_hostname[-1]}}.{{inventory_hostname[-1]}}"
        - redistribute connected
        - redistribute imported-ospf-routes
      parents: ['router ospf 100']
  - name: "Conf OSPF Tenant"
    os10_config:
      lines:
        - router-id "{{inventory_hostname[-1]}}.{{inventory_hostname[-1]}}.{{inventory_hostname[-1]}}.{{inventory_hostname[-1]}}"
        - redistribute connected
        - redistribute imported-ospf-routes
        - redistribute l2vpn evpn
      parents: ['router ospf 101 vrf Blue']
  - name: "Conf OSPF interface"
    os10_config:
      lines: ['ip ospf 101 area 0.0.0.0']
      parents: ['interface ethernet 1/1/3:1']
  - name: "Conf OSPF P2P link"
    os10_config:
      lines: ['ip ospf network point-to-point']
      parents: ['interface ethernet 1/1/3:1']

