switch_role: leaf

os10_system:
    hostname: Leaf5

os10_vrf:
    vrfdetails:
      - vrf_name: "Blue" 
        state: "present"
        ip_route_export:
          community_value: "20000:20000"
          route_map_value: "Xport-from-fabric-to-Ext"
          state: "present"
        ip_route_import:
          community_value: "60000:60000"
          route_map_value: "Xport-from-Ext-to-fabric"
          state: "present"
      - vrf_name: "Red"
        state: "present"
        ip_route_export:
          community_value: "40000:40000"
          route_map_value: "Xport-from-fabric-to-Ext"
          state: "present"
        ip_route_import:
          community_value: "60000:60000"
          route_map_value: "Xport-from-Ext-to-fabric"
          state: "present"
      - vrf_name: "Ext"
        state: "present"

os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.0.0.13/32
  ethernet 1/1/1:
    desc: "link to EXT RTR"
    switchport: False
    vrf: Ext
    mtu: 1532
    ip_and_mask: 192.168.201.1/24
  ethernet 1/1/13:
    desc: "Link to Spine1-Z9100-ON ethernet1/1/5"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.5.1.0/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/14:
    desc: "Link to Spine2-Z9100-ON ethernet1/1/5"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.5.2.0/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/15:
    desc: "VLT"
    switchport: False
    admin: up  
  virtual-network 10100:
    vrf: "Blue"
    ip_and_mask: 172.16.101.249/24
    virtual_gateway_ip: 172.16.101.254
    admin: up
  virtual-network 10200:
    vrf: "Blue"
    ip_and_mask: 172.16.102.249/24
    virtual_gateway_ip: 172.16.102.254
    admin: up
  virtual-network 10300:
    vrf: "Red"
    ip_and_mask: 172.16.103.249/24
    virtual_gateway_ip: 172.16.103.254
    admin: up
  virtual-network 10400:
    vrf: "Red"
    ip_and_mask: 172.16.104.249/24
    virtual_gateway_ip: 172.16.104.254
    admin: up

os10_vlt:
    domain: 1
    backup_destination: "192.168.114.18"
    destination_type: "ipv4"
    discovery_intf: 1/1/15
    discovery_intf_state: present
    peer_routing: True
    vlt_mac: 52:54:00:a5:87:13
    state: present

os10_prefix_list:
   - name: redistri-underlay
     type: ipv4
     entries:
       - number: 5
         permit: true
         net_num: 10.0.0.0
         mask: 24
         condition_list:
           - condition: ge
             prelen: 32
           - condition: le
             prelen: 32
         state: present
     state: present
   - name: Xport-from-fabric-to-Ext
     type: ipv4
     entries:
       - number: 5
         permit: true
         net_num: 172.16.0.0
         mask: 16
         condition_list:
           - condition: ge
             prelen: 24
           - condition: le
             prelen: 24
         state: present
     state: present
   - name: Xport-from-Ext-to-fabric
     type: ipv4
     entries:
       - number: 5
         permit: true
         net_num: 8.8.8.8
         mask: 32
         state: present
     state: present

os10_route_map:
  route_map:
    - name: redistri-underlay
      permit: true
      seq_num: 5
      match:
       - ip_type: ipv4
         prefix_list: redistri-underlay
      state: present
    - name: Xport-from-fabric-to-Ext
      permit: true
      seq_num: 5
      match:
       - ip_type: ipv4
         prefix_list: Xport-from-fabric-to-Ext
      state: present
    - name: Xport-from-Ext-to-fabric
      permit: true
      seq_num: 5
      match:
       - ip_type: ipv4
         prefix_list: Xport-from-Ext-to-fabric
      state: present


os10_bgp:
    asn: 65113
    router_id: 10.0.0.5
    redistribute:
      - route_type: connected
        address_type: ipv4
        route_map_name: redistri-underlay
        state: present
    neighbor:
      - type: ipv4
        interface: ethernet 1/1/13
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/14
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present

os10_vxlan:
    anycast_gateway_mac: 52:54:00:87:87:87
    nve:
      source_interface: 0
      state: present
    evpn:
      evi:
        - id: 10100
          vni: 
            id: 10100
            state: "present"
          rd: "auto"
          route_target:
            - type: "manual"
              asn_value: "10100:10100"
              route_target_type: "both"
              state: "present"
        - id: 10200
          vni: 
            id: 10200
            state: "present"
          rd: "auto"
          route_target:
            - type: "manual"
              asn_value: "10200:10200"
              route_target_type: "both"
              state: present
        - id: 10300
          vni:
            id: 10300
            state: "present"
          rd: "auto"
          route_target:
            - type: "manual"
              asn_value: "10300:10300"
              route_target_type: "both"
              state: present
        - id: 10400
          vni:
            id: 10400
            state: "present"
          rd: "auto"
          route_target:
            - type: "manual"
              asn_value: "10400:10400"
              route_target_type: "both"
              state: present
      vrf:
        - name: "Blue"
          vni: 20000
          adv_ipv4:
            - type: "connected"
              state: "present"
            - type: "ospf"
              state: "present"
          route_target:
            - type: "manual"
              asn_value: "20000:20000"
              route_target_type: "both"
              state: "present"
        - name: "Red"
          vni: 40000
          adv_ipv4:
            - type: "connected"
              state: "present"
            - type: "ospf"
              state: "present"
          route_target:
            - type: "manual"
              asn_value: "40000:40000"
              route_target_type: "both"
              state: "present"
        - name: "Ext"
      rmac: 52:54:00:87:87:13
    virtual_network:
      virtual_net:
        - id: 10100
          vxlan_vni:
            id: 10100
        - id: 10200
          vxlan_vni:
            id: 10200
        - id: 10300
          vxlan_vni:
            id: 10300
        - id: 10400
          vxlan_vni:
            id: 10400
