switch_role: spine

os10_system:
    hostname: Spine2

os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.0.99.2/32
  ethernet 1/1/1:
    desc: "Link to Leaf1-S5248-ON ethernet1/1/51"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.1.2.1/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/2:
    desc: "Link to Leaf2-S5248-ON ethernet1/1/51"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.2.2.1/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/3:
    desc: "Link to Leaf3-S5248-ON ethernet1/1/51"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.3.2.1/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/4:
    desc: "Link to Leaf4-S5248-ON ethernet1/1/51"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.4.2.1/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/5:
    desc: "Link to Leaf5-S4112-ON ethernet1/1/51"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.5.2.1/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/6:
    desc: "Link to Leaf6-S4112-ON ethernet1/1/51"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.6.2.1/31
    suppress_ra:
    min_ra: 3
    max_ra: 4

os10_prefix_list:
   - name: redistri-underlay
     type: ipv4
     entries:
       - number: 5
         permit: true
         net_num: 10.0.99.0
         mask: 24
         condition_list:
           - condition: ge
             prelen: 32
           - condition: le
             prelen: 32
         state: present
     state: present

os10_route_map:
  route_map:
    - name: redistri-underlay
      permit: true
      seq_num: 5
      match:
       - ip_type: ipv4
         prefix_list: redistri-underlay
      state: present

os10_bgp:
    asn: 65101
    router_id: 10.0.99.2
    redistribute:
      - route_type: connected
        address_type: ipv4
        route_map_name: redistri-underlay
        state: present
    neighbor:
      - type: ipv4
        interface: ethernet 1/1/1
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/2
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/3
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/4
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/5
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/6
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present

os10_vxlan:
    evpn:
      state: present


