switch_role: leaf

os10_system:
    hostname: Leaf2

os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.0.0.2/32
  ethernet 1/1/49:
    desc: "Link to Spine1-Z9100-ON ethernet1/1/2"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.2.1.0/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/51:
    desc: "Link to Spine2-Z9100-ON ethernet1/1/2"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.2.2.0/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/55:
    desc: "VLT 1"
    switchport: False
    admin: up
  ethernet 1/1/56:
    desc: "VLT 2"
    switchport: False
    admin: up

os10_vlt:
    domain: 1
    backup_destination: "192.168.114.13"
    destination_type: "ipv4"
    discovery_intf: 1/1/55, 1/1/56
    discovery_intf_state: present
    peer_routing: True
    vlt_mac: 52:54:00:a5:87:11
    state: present

os10_bgp:
    asn: 65111
    router_id: 10.0.0.2
    redistribute:
      - route_type: connected
        address_type: ipv4
        state: present
    neighbor:
      - type: ipv4
        interface: ethernet 1/1/49
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/51
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present


