switch_role: leaf

os10_system:
    hostname: Leaf5

os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.0.0.13/32
  ethernet 1/1/13:
    desc: "Link to Spine1-Z9100-ON ethernet1/1/5"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.5.1.0/31
    suppress_ra:
    min_ra: 3
    max_ra: 4
  ethernet 1/1/14:
    desc: "Link to Spine2-Z9100-ON ethernet1/1/5"
    switchport: False
    admin: up
    mtu: 9216
#    ip_and_mask: 10.5.2.0/31
    suppress_ra:
    min_ra: 3
    max_ra: 4

  ethernet 1/1/15:
    desc: "VLT"
    switchport: False
    admin: up  

os10_vlt:
    domain: 1
    backup_destination: "192.168.114.18"
    destination_type: "ipv4"
    discovery_intf: 1/1/15
    discovery_intf_state: present
    peer_routing: True
    vlt_mac: 52:54:00:a5:87:13
    state: present

os10_prefix_list:
   - name: redistri-underlay
     type: ipv4
     entries:
       - number: 5
         permit: true
         net_num: 10.0.0.0
         mask: 24
         condition_list:
           - condition: ge
             prelen: 32
           - condition: le
             prelen: 32
         state: present
     state: present

os10_route_map:
  route_map:
    - name: redistri-underlay
      permit: true
      seq_num: 5
      match:
       - ip_type: ipv4
         prefix_list: redistri-underlay
      state: present

os10_bgp:
    asn: 65113
    router_id: 10.0.0.5
    redistribute:
      - route_type: connected
        address_type: ipv4
        route_map_name: redistri-underlay
        state: present
    neighbor:
      - type: ipv4
        interface: ethernet 1/1/13
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present
      - type: ipv4
        interface: ethernet 1/1/14
        send_community:
          - type: extended
            state: present
        address_family:
          - type: l2vpn
            activate: true
            state: present
        admin: up
        state: present


