switch_role: leaf

os10_system:
    hostname: Leaf3

os10_interface:
  loopback 0:
    admin: up
    ip_and_mask: 10.0.0.3/32
  ethernet 1/1/55:
    desc: "VLT 1"
    switchport: False
    admin: up
  ethernet 1/1/56:
    desc: "VLT 2"
    switchport: False
    admin: up

os10_vlt:
    domain: 1
    backup_destination: "192.168.114.16"
    destination_type: "ipv4"
    discovery_intf: 1/1/55, 1/1/56
    discovery_intf_state: present
    peer_routing: True
    vlt_mac: 52:54:00:a5:87:12
    state: present
